_id: 69fae2e14e03ce1d4bdd1796
name: new-fn
language: javascript
timeout: 10
triggers:
  default:
    type: http
    active: true
    options:
      method: Get
      path: /testasdqwe
      preflight: true
      authenticate: []
      authorize: false
memoryLimit: 100
