_id: 69f5c41665469f6be804f9c6
title: VC Test
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      translate: false
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      translate: false
acl:
  write: true==true
  read: true==true
order: 0
indexes: []
